version: "3.8"

services:
  my_app:
    build: .
    image: joshrichhy/crossfund:latest
    ports:
      - "8082:8081"
    env_file:
      - .env
    environment:
      PORT: "8081"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    restart: on-failure:3

  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - crossfund_web_net

networks:
  crossfund_web_net:
    driver: bridge

volumes:
  mongodb_data:
